# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RSSReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RSSReader
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRelay'
  pod 'SnapKit'
  pod 'FeedKit'
  pod 'SwiftSoup'
  pod 'Kingfisher'
  pod 'RealmSwift'
  
  target 'RSSReaderTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
  end

  target 'RSSReaderUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
                config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
          end
    end
end
