# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'RSSReader' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RSSReader
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'SnapKit'
  pod 'FeedKit'
  pod 'SwiftSoup'
  pod 'Kingfisher'
  
  target 'RSSReaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RSSReaderUITests' do
    # Pods for testing
  end

end
